# Generated by Django 2.1.3 on 2018-11-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_tipoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.TipoEvento'),
            preserve_default=False,
        ),
    ]
